### ISSUE TITLE
invalid yaml output

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-ai#49]
### What happened?

invalid YAML output.

> Notice a bug or have a feature request? Open an issue [on GitHub](https://github.com/pulumi/pulumi-ai/issues)!

If invalid outputs are not of concern, def close the issue.

```yaml
name: pulumi-random-error
runtime: nodejs
description: Reproduce update error for pulumi-random with resource outputs as inputs to others
main  - name: randomString
    type: random:index/randomStringRandomString
    args      length 10
      special false
  - name: randomPet
    type: random:index/randomPet:RandomPet
    args:
      length: "{{.outputs.length}}"
      prefix: "{{.outputs.result}}"
    dependsOn:
      - randomString
```
https://www.pulumi.com/ai/?convid=b4113e10-322c-4fba-b4b6-7c144d181232

### Expected Behavior

valid YAML output.

### Steps to reproduce

see link

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
